### ISSUE TITLE
Зачем 

### ISSUE THREAD

**Issue by paveL1boyko** [flaming-chameleon/random-user-agents#1]
Есть же либа которая это  делает ? 😁😁fake user agent ?

**Comment by flaming-chameleon** [comment]
Та либа устаревшая. Если хочешь что бы твои акки отлетели в бан то можешь и дальше ней пользоваться

**Comment by paveL1boyko** [comment]
Интересно как ты это решил 😁😁

**Comment by paveL1boyko** [comment]
В смысле у юзеров телефоны устарели 🤣🤣🤣

**Comment by flaming-chameleon** [comment]
Логику вруби, сколько сейчас пользователь использует андроид 4,5,6? Дам подсказку МАЛО, бля ну это все должны понимать ботоводы что это палево когда все используют агенты старых XP Windows и андроидов то ничего они не получат
